### ISSUE TITLE
Retirer les mots de plus de 5 caractères pour sauver la planète

### ISSUE THREAD

**Issue by Dorpaxio** [LouanBen/wordle-fr#27]
Imaginez un monde sans mots inutiles dans mots.txt...

**Comment by richie3366** [comment]
Il me semble que c'était intentionnel de le laisser tel quel (cc @LouanBen @Loji310), notamment pour que chacun puisse faire une variante différente (mots à taille variable par exemple) dans un fork hypothétique.

+ Le titre semble manquer d'exhaustivité puisqu'on pourrait dans la foulée se débarrasser des mots qui font moins de 5 caractères. :)

**Comment by Dorpaxio** [comment]
Tout à fait d'accord sur tous les points, voilà une bonne chose de faite @richie3366
