### ISSUE TITLE
Mauvaise barre en vert dans les statistiques

### ISSUE THREAD

**Issue by slimCODE** [LouanBen/wordle-fr#33]
Pour être fidèle avec la version anglaise (Wordle), la barre en vert dans les statistiques doit être celle de la dernière partie, et non celle avec le plus grand nombre. L'implémentation actuelle semble mettre en vert la barre au plus grand nombre.

**Comment by richie3366** [comment]
Merci pour nous avoir fait remonter cette incohérence (que je viens de vérifier à l'instant).

Avant de commencer à travailler sur un fix, je préfère demander à @LouanBen de donner son avis sur le fait de changer ou non le comportement pour ce motif-là.

À titre personnel, je pense effectivement qu'il serait mieux de mettre en surbrillance le dernier "score", puisqu'il est déjà aisé (soit par la taille des barres, soit par les nombres) de percevoir lequel est prépondérant. D'ailleurs, je me souviens avoir déjà mal interprété cette barre, puis de me rendre compte que c'était le score ayant le plus grand nombre.

**Comment by LouanBen** [comment]
Yes c'était un (mauvais) choix de ma part que de changer ça.

Ça en a perdu plus d'un•e donc je suis ok pour qu'on change ça !

Si @richie3366 tu veux t'en occuper, je te laisse faire une PR, sinon je m'en charge :)

**Comment by richie3366** [comment]
Je te la laisse, de mon côté je m'occuperai du streak ce soir. ;)

**Comment by LouanBen** [comment]
Ça a été mis à jour, merci encore !
