### ISSUE TITLE
Informer les utilisateurs de Safari

### ISSUE THREAD

**Issue by Kekwel** [LouanBen/wordle-fr#36]
Bonjour !

Impossible de partager le résultat sur Safari. Car il est impossible de mettre qqchose dans le’ presse papier truc dans le genre ?

Alors je suis sur un iPhone 6, je ne sais pas la version de safari.

Pouvoir prévenir via une notif ou autres, un peu comme SUTOM lorsque l’on clique sur partager.
![95696C7C-EFD2-4869-AED3-D7CF4B221F59](https://user-images.githubusercontent.com/9060357/150971418-6da54201-9b5f-4e01-9297-3a158dfc0b97.jpeg)

**Comment by richie3366** [comment]
Vérification faite, la méthode `Clipboard.writeText` n'est supportée qu'à partir de Safari 13.4, qui n'est disponible que pour les iPhone sortis après le 6, càd à partir du 6s & ultérieurs.

Concertation faite avec @LouanBen, on va pour l'instant mettre un message d'erreur via une simple alerte. Plus tard, on mettra probablement une modale d'erreur avec un champ de texte prérempli (pour permettre copier manuellement).

**Comment by LouanBen** [comment]
Un warning a été mis, mais on va réfléchir à une solution alternative pour ceux qui ne peuvent pas copier via un bouton :)

**Comment by Kekwel** [comment]
Merci à vous pour votre réactivité !
J'aurai volontiers tenter une PR mais j'ai très peu de temps libre en ce moment :/
