### ISSUE TITLE
On ne peut pas voir le temps avant le prochain mot sur mobile

### ISSUE THREAD

**Issue by clepeterd** [LouanBen/wordle-fr#41]
Bonjour,

Superbe jeu.  Il semble que sur mobile, du moins sur un iphone SE 2en generation avec chrome, il soit impossible de faire défiler la page pour voir le temps restant avant le prochain coup.  Le tout semble caché en bas de la barre de status de google chrome.

Sur Android sur un Galaxy S20FE c'est pas mal la même chose.

Merci

**Comment by LouanBen** [comment]
Coucou @clepeterd !
Merci pour cette issue.

Est-ce que tu pourrais aller sur le site https://whatismyviewport.com/ avec le (ou les ?) portable(s) que tu utilise pour jouer, avec le(s) même(s) navigateur(s), et m'indiquer quelles dimensions apparaissent ?

Ça dépend un peu de chacun, du portable, du navigateur, des paramètres sur le portable... À chaque fois que je pense avoir réglé tous les cas de figures, quelqu'un arrive avec une interface encore plus petite ahah

Dès que j'ai les dimensions de ton viewport, je travaille sur une solution :) !

**Comment by clepeterd** [comment]
Bonjour, voici pour le iphone avec chrome

**Comment by clepeterd** [comment]
Et sur mon gakaxy s20fe

**Comment by richie3366** [comment]
@clepeterd Il semblerait que github ne tienne pas compte des images dans une réponse faite par e-mail. Je crains malheureusement qu'il faille les renvoyer (depuis la page de commentaires de l'issue).

**Comment by clepeterd** [comment]
[drive-download-20220131T201517Z-001.zip](https://github.com/LouanBen/wordle-fr/files/7973941/drive-download-20220131T201517Z-001.zip)

Voici les deux screenshots 375x553 = Iphone 5 2nd Gen
339 x 622 = Galaxy S20FE

**Comment by richie3366** [comment]
Apparemment ça devrait avoir été résolu entretemps, je clos. Si jamais le problème est encore d'actualité, je t'invite à rouvrir et à ajouter un commentaire. Merci
