### ISSUE TITLE
Broken link "Soutenir l'auteur du projet"

### ISSUE THREAD

**Issue by adicrl** [LouanBen/wordle-fr#65]
The support link on the Statistiques page shows a 404. The utip service seems retired:
https://utip.io/louanben
https://utip.io

**Comment by LouanBen** [comment]
Yes, the utip website permanently went down 2 months ago.
I have yet to find a replacement.

**Comment by LouanBen** [comment]
The link was updated today in branch #66.
If anyone wants to support the project, it is now possible on Ko-fi :)

Thanks for the issue @adicrl !
